version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: intergalactic_db
    environment:
      POSTGRES_USER: ${DATABASE_USER:-intergalactic}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-intergalactic_teacher}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-intergalactic} -d ${DATABASE_NAME:-intergalactic_teacher}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - intergalactic_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: intergalactic_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - intergalactic_network

  # Backend API
  api:
    build: .
    container_name: intergalactic_api
    ports:
      - "8000:8000"
      - "9001:9000"
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-intergalactic}:${DATABASE_PASSWORD:-password}@db:5432/${DATABASE_NAME:-intergalactic_teacher}
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - LANGSMITH_TRACING=true
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_API_KEY=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
      - LANGSMITH_PROJECT=intergalactic-teacher
    volumes:
      - .:/app
      - /app/__pycache__
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - intergalactic_network
    restart: unless-stopped

  # Development tools (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: intergalactic_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@intergalactic.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - intergalactic_network
    profiles:
      - dev

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: intergalactic_redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - intergalactic_network
    profiles:
      - dev

volumes:
  postgres_data:
  redis_data:

networks:
  intergalactic_network:
    driver: bridge