import { useState, useCallback, useMemo, useEffect, useRef } from 'react';
import { useStoryStore } from '../stores/storyStore';
import { useChildStore } from '../stores/childStore';
import type { Choice } from '../types';

interface StoryMessage {
  id: string;
  role: 'assistant' | 'user' | 'system';
  content: Array<{ type: 'text'; text: string }>;
  createdAt: Date;
  metadata?: {
    chapterNumber?: number;
    storyId?: string;
    choices?: Choice[];
  };
}

interface StoryRuntimeState {
  messages: StoryMessage[];
  isLoading: boolean;
  sessionId: string | null;
  isInitialized: boolean;
  usedChoiceMessageIds: Set<string>;
}

export const useStoryRuntime = () => {
  const { currentStory, makeChoice, isLoading, startSession, streamingState } = useStoryStore();
  const { currentChild } = useChildStore();

  const [state, setState] = useState<StoryRuntimeState>({
    messages: [],
    isLoading: false,
    sessionId: null,
    isInitialized: false,
    usedChoiceMessageIds: new Set(),
  });

  // Track current story ID to detect story changes
  const [currentStoryId, setCurrentStoryId] = useState<string | null>(null);

  // Reset session when story changes
  useEffect(() => {
    if (currentStory && currentStory.id !== currentStoryId) {
      console.log('🔄 Story changed - resetting session', { oldId: currentStoryId, newId: currentStory.id });
      setState({
        messages: [],
        isLoading: false,
        sessionId: null,
        isInitialized: false,
        usedChoiceMessageIds: new Set(),
      });
      setCurrentStoryId(currentStory.id);
    }
  }, [currentStory, currentStoryId]);

  // Add choices to the last message after streaming completes
  useEffect(() => {
    // Skip if no story, not initialized yet, or still streaming
    if (!currentStory || !state.isInitialized || streamingState.isStreaming) return;

    // Skip if no choices
    if (!currentStory.choices || currentStory.choices.length === 0) return;

    // Check if we need to add choices
    setState(prev => {
      if (prev.messages.length === 0) return prev;

      const lastMessage = prev.messages[prev.messages.length - 1];

      // Only add if the last message doesn't already have choices
      if (lastMessage.role === 'assistant' && !lastMessage.metadata?.choices) {
        console.log('📎 Attaching choices to last message after streaming completed', {
          messageId: lastMessage.id,
          choicesCount: currentStory.choices.length
        });

        return {
          ...prev,
          messages: [
            ...prev.messages.slice(0, -1),
            {
              ...lastMessage,
              metadata: {
                ...lastMessage.metadata,
                choices: currentStory.choices
              }
            }
          ]
        };
      }

      return prev;
    });
  }, [currentStory, currentStory?.choices, streamingState.isStreaming, state.isInitialized]);

  // Initialize story session and first message
  const initializeStory = useCallback(async () => {
    if (!currentStory || !currentChild || state.sessionId || state.isInitialized) return;

    try {
      setState(prev => ({ ...prev, isLoading: true }));

      const sessionResponse = await startSession({
        storyId: currentStory.id,
        childId: currentChild.id.toString()
      });

      const sessionId = sessionResponse.session ? sessionResponse.session.id.toString() : (sessionResponse as any).id.toString();

      // For existing stories, load all previous chapters
      // Welcome message will be generated by LLM and streamed from backend
      const messagesToAdd: StoryMessage[] = [];

      // If this is an existing story with content, add all chapters up to current
      // BUT: Don't load content if we're currently streaming (story is being generated)
      if (currentStory.content && currentStory.content.length > 0 && !streamingState.isStreaming) {
        // If content is an array, each element is a separate chapter
        if (Array.isArray(currentStory.content)) {
          // Add each chapter as a separate message
          currentStory.content.forEach((chapterContent, index) => {
            const chapterNumber = index + 1;
            const chapterMessage: StoryMessage = {
              id: `chapter-${chapterNumber}-${Date.now()}-${index}`,
              role: 'assistant',
              content: [{ type: 'text', text: chapterContent }],
              createdAt: new Date(Date.now() + index * 1000), // Slight delay for ordering
              metadata: {
                storyId: currentStory.id,
                chapterNumber: chapterNumber
              }
            };
            messagesToAdd.push(chapterMessage);
          });
        } else {
          // Single content block - treat as one chapter
          const chapterMessage: StoryMessage = {
            id: `chapter-${currentStory.currentChapter}-${Date.now()}`,
            role: 'assistant',
            content: [{ type: 'text', text: currentStory.content }],
            createdAt: new Date(),
            metadata: {
              storyId: currentStory.id,
              chapterNumber: currentStory.currentChapter
            }
          };
          messagesToAdd.push(chapterMessage);
        }

        // Add choices if available (only after the last chapter)
        // NOTE: The choice question is already in the story content from the LLM
        // We just need to attach the choices metadata to the last message
        if (currentStory.choices && currentStory.choices.length > 0) {
          // Find the last chapter message and add choices to it
          const lastMessageIndex = messagesToAdd.length - 1;
          if (lastMessageIndex >= 0) {
            messagesToAdd[lastMessageIndex] = {
              ...messagesToAdd[lastMessageIndex],
              metadata: {
                ...messagesToAdd[lastMessageIndex].metadata,
                choices: currentStory.choices
              }
            };
          }
        }
      }

      setState(prev => ({
        ...prev,
        messages: messagesToAdd,
        sessionId,
        isLoading: false,
        isInitialized: true
      }));

      // Don't auto-send first chapter here since we already added it

    } catch (error) {
      console.error('Failed to initialize story:', error);
      setState(prev => ({ ...prev, isLoading: false }));
    }
  }, [currentStory, currentChild, startSession, state.sessionId, state.isInitialized]);

  // Send current chapter as single chat message
  const sendCurrentChapter = useCallback(() => {
    if (!currentStory || !currentStory.content || currentStory.content.length === 0) return;

    // Combine all paragraphs into single chat message
    const chapterText = Array.isArray(currentStory.content)
      ? currentStory.content.join('\n\n')
      : currentStory.content;

    const messageId = `chapter-${currentStory.currentChapter}-${Date.now()}`;

    const chapterMessage: StoryMessage = {
      id: messageId,
      role: 'assistant',
      content: [{ type: 'text', text: chapterText }],
      createdAt: new Date(),
      metadata: {
        storyId: currentStory.id,
        chapterNumber: currentStory.currentChapter
      }
    };

    setState(prev => ({
      ...prev,
      messages: [...prev.messages, chapterMessage]
    }));

    // Send choices if available
    if (currentStory.choices && currentStory.choices.length > 0) {
      setTimeout(() => {
        // Check if choices for this chapter are already in messages
        const hasChoicesForCurrentChapter = state.messages.some(msg =>
          msg.metadata?.choices && msg.metadata?.chapterNumber === currentStory.currentChapter
        );

        if (!hasChoicesForCurrentChapter) {
          sendChoiceOptions(currentStory.choices!);
        }
      }, 1000);
    }
  }, [currentStory]);

  // Send choice options
  const sendChoiceOptions = useCallback((choices: Choice[]) => {
    // NOTE: The choice question is already in the story content from the LLM
    // We just need to attach the choices metadata to the last message
    // Don't create a new message with the question - it would be a duplicate!

    setState(prev => {
      const newMessages = [...prev.messages];
      const lastMessageIndex = newMessages.length - 1;

      if (lastMessageIndex >= 0) {
        // Attach choices to the last message
        newMessages[lastMessageIndex] = {
          ...newMessages[lastMessageIndex],
          metadata: {
            ...newMessages[lastMessageIndex].metadata,
            choices,
            chapterNumber: currentStory?.currentChapter
          }
        };
      }

      return {
        ...prev,
        messages: newMessages
      };
    });
  }, [currentStory?.currentChapter]);

  // Handle user choice selection
  const handleChoice = useCallback(async (choiceId: string, optionIndex: number, choiceText: string, messageId: string) => {
    if (!state.sessionId) return;

    try {
      setState(prev => ({ ...prev, isLoading: true }));

      // Mark this message's choices as used
      setState(prev => {
        const newUsedIds = new Set(prev.usedChoiceMessageIds);
        newUsedIds.add(messageId);
        return {
          ...prev,
          usedChoiceMessageIds: newUsedIds
        };
      });

      // Add user choice message
      const userMessage: StoryMessage = {
        id: `choice-${Date.now()}`,
        role: 'user',
        content: [{ type: 'text', text: choiceText }],
        createdAt: new Date()
      };

      setState(prev => ({
        ...prev,
        messages: [...prev.messages, userMessage]
      }));

      // Make the choice via the story store - this will generate next chapter
      await makeChoice(state.sessionId, {
        choiceId,
        optionIndex,
        timestamp: new Date().toISOString()
      });

      setState(prev => ({ ...prev, isLoading: false }));

      // The makeChoice call will update currentStory in the store with new chapter content
      // The useEffect watching currentStory changes will handle sending the new chapter automatically

    } catch (error) {
      console.error('Failed to make choice:', error);
      setState(prev => ({ ...prev, isLoading: false }));
    }
  }, [state.sessionId, makeChoice, sendCurrentChapter]);

  // Handle custom text input as a story choice
  const handleCustomChoice = useCallback(async (customText: string) => {
    if (!state.sessionId || !customText.trim()) return;

    try {
      setState(prev => ({ ...prev, isLoading: true }));

      // Add user custom message
      const userMessage: StoryMessage = {
        id: `custom-choice-${Date.now()}`,
        role: 'user',
        content: [{ type: 'text', text: customText }],
        createdAt: new Date()
      };

      setState(prev => ({
        ...prev,
        messages: [...prev.messages, userMessage]
      }));

      // Make the custom choice via the story store using a generic choice ID
      await makeChoice(state.sessionId, {
        choiceId: 'custom-choice',
        optionIndex: 0,
        timestamp: new Date().toISOString(),
        customText: customText.trim()
      });

      setState(prev => ({ ...prev, isLoading: false }));

    } catch (error) {
      console.error('Failed to make custom choice:', error);
      setState(prev => ({ ...prev, isLoading: false }));
    }
  }, [state.sessionId, makeChoice]);

  // Simple runtime object for assistant-ui
  const runtime = useMemo(() => {
    return {
      messages: state.messages,
      isLoading: state.isLoading || isLoading,
      usedChoiceMessageIds: state.usedChoiceMessageIds,

      append: async (message: any) => {
        // Handle user messages (choices)
        if (message.role === 'user') {
          const content = Array.isArray(message.content)
            ? message.content.find((c: any) => c.type === 'text')?.text || ''
            : message.content;

          // Check if this is a choice selection
          const lastMessage = state.messages[state.messages.length - 1];
          if (lastMessage?.metadata?.choices) {
            const choice = lastMessage.metadata.choices.find(c =>
              c.text.includes(content) || content.includes(c.text)
            );
            if (choice) {
              await handleChoice(choice.id, choice.option_index, choice.text, lastMessage.id);
              return;
            }
          }

          // Handle "start story" messages (yes, ready, continue, etc.)
          if (content.toLowerCase().includes('yes') ||
            content.toLowerCase().includes('ready') ||
            content.toLowerCase().includes('start') ||
            content.toLowerCase().includes('begin') ||
            content.toLowerCase().includes('continue') ||
            content.toLowerCase().includes('next') ||
            content.toLowerCase().includes('go') ||
            content.toLowerCase().includes('כן') ||
            content.toLowerCase().includes('מוכן') ||
            content.toLowerCase().includes('התחל') ||
            content.toLowerCase().includes('המשך')) {
            sendCurrentChapter();
            return;
          }

          // If we have an active session and it's not just a start command,
          // treat any user input as a custom choice that should advance the story
          if (state.sessionId && content.trim().length > 0) {
            await handleCustomChoice(content);
            return;
          }
        }
      },

      thread: {
        mainItem: {
          id: 'main',
          messages: state.messages
        }
      }
    };
  }, [state, isLoading, handleChoice, handleCustomChoice, sendCurrentChapter]);

  // Auto-initialize when story is available
  useEffect(() => {
    if (currentStory && currentChild && !state.sessionId && !state.isInitialized) {
      initializeStory();
    }
  }, [currentStory, currentChild, state.sessionId, state.isInitialized, initializeStory]);

  // Watch for streaming content during story generation
  useEffect(() => {
    console.log('🔄 Streaming useEffect triggered:', {
      isStreaming: streamingState.isStreaming,
      contentLength: streamingState.streamedContent?.length,
      isInitialized: state.isInitialized
    });

    if (streamingState.isStreaming && streamingState.streamedContent && state.isInitialized) {
      // Find or create the streaming message
      const streamingMessageId = `streaming-${currentStory?.id || 'temp'}`;
      const existingMessageIndex = state.messages.findIndex(m => m.id === streamingMessageId);

      // console.log('📝 Updating streaming message:', {
      //   messageId: streamingMessageId,
      //   existingIndex: existingMessageIndex,
      //   contentPreview: streamingState.streamedContent.substring(0, 50)
      // });

      if (existingMessageIndex >= 0) {
        // Update existing streaming message
        setState(prev => {
          const newMessages = [...prev.messages];
          newMessages[existingMessageIndex] = {
            ...newMessages[existingMessageIndex],
            content: [{ type: 'text', text: streamingState.streamedContent }],
            metadata: {
              ...newMessages[existingMessageIndex].metadata,
              chapterNumber: currentStory?.currentChapter
            }
          };
          return { ...prev, messages: newMessages };
        });
      } else {
        // Create new streaming message
        const streamingMessage: StoryMessage = {
          id: streamingMessageId,
          role: 'assistant',
          content: [{ type: 'text', text: streamingState.streamedContent }],
          createdAt: new Date(),
          metadata: {
            storyId: currentStory?.id,
            chapterNumber: currentStory?.currentChapter
          }
        };
        setState(prev => ({
          ...prev,
          messages: [...prev.messages, streamingMessage]
        }));
      }
    } else if (!streamingState.isStreaming && state.isInitialized) {
      // When streaming stops, convert the streaming message to a permanent chapter message
      const streamingMessageId = `streaming-${currentStory?.id || 'temp'}`;
      const streamingMessageIndex = state.messages.findIndex(m => m.id === streamingMessageId);

      if (streamingMessageIndex >= 0) {
        // Convert the streaming message to a permanent chapter message
        setState(prev => {
          const newMessages = [...prev.messages];
          const streamingMessage = newMessages[streamingMessageIndex];

          // Replace streaming message with permanent chapter message
          newMessages[streamingMessageIndex] = {
            ...streamingMessage,
            id: `chapter-${currentStory?.currentChapter}-${Date.now()}`,
            metadata: {
              ...streamingMessage.metadata,
              storyId: currentStory?.id,
              chapterNumber: currentStory?.currentChapter
            }
          };

          return { ...prev, messages: newMessages };
        });
      }
    }
  }, [streamingState.isStreaming, streamingState.streamedContent, state.isInitialized, currentStory?.id, currentStory?.currentChapter]);

  // Watch for story content changes (new chapters from backend)
  useEffect(() => {
    if (currentStory && currentStory.content && state.sessionId && state.isInitialized) {
      // Check if we have messages and if the latest chapter is already displayed
      const lastStoryMessage = state.messages
        .filter(msg => msg.metadata?.chapterNumber)
        .pop();

      const currentChapterInMessages = lastStoryMessage?.metadata?.chapterNumber || 0;

      // If we have a new chapter from backend that's not yet displayed, send it to chat
      // BUT: Don't send if chapters were already loaded during initialization
      // (when content is an array, all chapters are loaded in initializeStory)
      const chaptersLoadedDuringInit = Array.isArray(currentStory.content) && currentStory.content.length > 0;

      if (currentStory.currentChapter > currentChapterInMessages && !chaptersLoadedDuringInit) {
        // Add a delay for better UX, especially for first chapter after welcome
        const delay = state.messages.length === 1 ? 1500 : 500; // Longer delay after welcome
        setTimeout(() => {
          sendCurrentChapter();
        }, delay);
      }
    }
  }, [currentStory?.currentChapter, currentStory?.content, state.sessionId, state.messages, state.isInitialized, sendCurrentChapter]);

  // Watch for choices after streaming completes
  // Use a ref to track if we were previously streaming
  const wasStreamingRef = useRef(false);

  useEffect(() => {
    // Only add choices if we just finished streaming (transition from true to false)
    const justFinishedStreaming = wasStreamingRef.current && !streamingState.isStreaming;
    wasStreamingRef.current = streamingState.isStreaming;

    // console.log('🎯 Choices effect triggered:', {
    //   justFinishedStreaming,
    //   hasChoices: !!currentStory?.choices,
    //   choicesCount: currentStory?.choices?.length,
    //   currentChapter: currentStory?.currentChapter,
    //   isInitialized: state.isInitialized
    // });

    if (justFinishedStreaming && currentStory?.choices && currentStory.choices.length > 0 && state.isInitialized) {
      // Check if choices are already displayed for current chapter
      const hasChoicesForCurrentChapter = state.messages.some(msg =>
        msg.metadata?.choices && msg.metadata?.chapterNumber === currentStory.currentChapter
      );

      console.log('💡 Streaming finished:', {
        hasChoicesForCurrentChapter,
        currentChapter: currentStory.currentChapter,
        choices: currentStory.choices
      });

      if (!hasChoicesForCurrentChapter) {
        console.log('✅ Adding choices to messages');
        setTimeout(() => {
          sendChoiceOptions(currentStory.choices!);
        }, 500); // Small delay after streaming stops
      } else {
        console.log('⏭️ Choices already exist for this chapter');
      }
    }
  }, [streamingState.isStreaming, currentStory?.choices, currentStory?.currentChapter, state.isInitialized, state.messages, sendChoiceOptions]);

  return runtime;
};