"""Initial migration with all tables

Revision ID: 0d1291b6e455
Revises: 
Create Date: 2025-08-27 19:28:47.702349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1291b6e455'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('hebrew', 'english', name='story_language_enum'), nullable=False),
    sa.Column('difficulty_level', sa.Enum('beginner', 'intermediate', 'advanced', name='story_difficulty_enum'), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('target_age_min', sa.Integer(), nullable=True),
    sa.Column('target_age_max', sa.Integer(), nullable=True),
    sa.Column('estimated_reading_time', sa.Integer(), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('has_choices', sa.Boolean(), nullable=True),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('content_safety_score', sa.Float(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('language_preference', sa.Enum('hebrew', 'english', name='language_enum'), nullable=True),
    sa.Column('reading_level', sa.Enum('beginner', 'intermediate', 'advanced', name='reading_level_enum'), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('total_stories_completed', sa.Integer(), nullable=True),
    sa.Column('total_reading_time', sa.Integer(), nullable=True),
    sa.Column('current_reading_streak', sa.Integer(), nullable=True),
    sa.Column('longest_reading_streak', sa.Integer(), nullable=True),
    sa.Column('vocabulary_words_learned', sa.Integer(), nullable=True),
    sa.Column('reading_level_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('position_in_chapter', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('choices_data', sa.JSON(), nullable=False),
    sa.Column('default_choice_index', sa.Integer(), nullable=True),
    sa.Column('is_critical_choice', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_choices_id'), 'choices', ['id'], unique=False)
    op.create_table('story_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.Column('choice_option_index', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('leads_to_chapter', sa.Integer(), nullable=True),
    sa.Column('leads_to_choice_id', sa.Integer(), nullable=True),
    sa.Column('is_ending', sa.Boolean(), nullable=True),
    sa.Column('difficulty_modifier', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['leads_to_choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_branches_id'), 'story_branches', ['id'], unique=False)
    op.create_table('story_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('current_chapter', sa.Integer(), nullable=True),
    sa.Column('current_choice_id', sa.Integer(), nullable=True),
    sa.Column('choices_made', sa.JSON(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('words_read', sa.Integer(), nullable=True),
    sa.Column('audio_playback_used', sa.Boolean(), nullable=True),
    sa.Column('audio_playback_duration', sa.Integer(), nullable=True),
    sa.Column('choices_engagement_rate', sa.Integer(), nullable=True),
    sa.Column('reading_speed_wpm', sa.Integer(), nullable=True),
    sa.Column('pause_count', sa.Integer(), nullable=True),
    sa.Column('vocabulary_encountered', sa.JSON(), nullable=True),
    sa.Column('comprehension_score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['current_choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_sessions_id'), 'story_sessions', ['id'], unique=False)
    op.create_table('user_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=True),
    sa.Column('total_reading_time', sa.Integer(), nullable=True),
    sa.Column('words_read', sa.Integer(), nullable=True),
    sa.Column('stories_completed', sa.Integer(), nullable=True),
    sa.Column('stories_started', sa.Integer(), nullable=True),
    sa.Column('average_session_duration', sa.Integer(), nullable=True),
    sa.Column('choices_made', sa.Integer(), nullable=True),
    sa.Column('audio_playback_time', sa.Integer(), nullable=True),
    sa.Column('pause_frequency', sa.Float(), nullable=True),
    sa.Column('reading_speed_wpm', sa.Integer(), nullable=True),
    sa.Column('comprehension_score', sa.Float(), nullable=True),
    sa.Column('vocabulary_words_learned', sa.Integer(), nullable=True),
    sa.Column('reading_level_improvement', sa.Float(), nullable=True),
    sa.Column('preferred_themes', sa.JSON(), nullable=True),
    sa.Column('preferred_difficulty', sa.String(), nullable=True),
    sa.Column('best_reading_time', sa.String(), nullable=True),
    sa.Column('attention_span_minutes', sa.Integer(), nullable=True),
    sa.Column('return_likelihood', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_analytics_id'), 'user_analytics', ['id'], unique=False)
    op.create_table('story_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_from_choice_id', sa.Integer(), nullable=True),
    sa.Column('created_from_branch_id', sa.Integer(), nullable=True),
    sa.Column('is_ending', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('estimated_reading_time', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_from_branch_id'], ['story_branches.id'], ),
    sa.ForeignKeyConstraint(['created_from_choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_chapters_id'), 'story_chapters', ['id'], unique=False)
    op.create_index(op.f('ix_story_chapters_story_id'), 'story_chapters', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_chapters_story_id'), table_name='story_chapters')
    op.drop_index(op.f('ix_story_chapters_id'), table_name='story_chapters')
    op.drop_table('story_chapters')
    op.drop_index(op.f('ix_user_analytics_id'), table_name='user_analytics')
    op.drop_table('user_analytics')
    op.drop_index(op.f('ix_story_sessions_id'), table_name='story_sessions')
    op.drop_table('story_sessions')
    op.drop_index(op.f('ix_story_branches_id'), table_name='story_branches')
    op.drop_table('story_branches')
    op.drop_index(op.f('ix_choices_id'), table_name='choices')
    op.drop_table('choices')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###