"""rename_full_name_to_name

Revision ID: 179400ee2fd3
Revises: 7b518bd04911
Create Date: 2025-08-26 16:56:21.649174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179400ee2fd3'
down_revision = '7b518bd04911'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###